---
- hosts: dev
  become: true

  tasks:
  - name: Fetch files
    fetch:
      src: /home/saksham/cv_web.tar
      dest: /home/saksham/ansible/
      flat: yes

  - name: Download files
    get_url:
      url: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/z/Zim-0.75.2-8.el9.noarch.rpm
      dest: /home
    tags:
    - download
